#! /bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/var/ucx_meter/cfg/run-meter
PIDFILE=/var/run/run-meter.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting feedparser"
     start-stop-daemon --pidfile $PIDFILE --startas $DAEMON --start
     echo $!
     log_end_msg $?
   ;;
  stop)
     log_daemon_msg "Stopping feedparser"
     start-stop-daemon --pidfile $PIDFILE --stop
     log_end_msg $?
   ;;
  force-reload|restart)
     $0 stop
     $0 start
   ;;
  status)
     status_of_proc -p $PIDFILE $DAEMON atd && exit 0 || exit $?
   ;;
 *)
   echo "Usage: /etc/init.d/atd {start|stop|restart|force-reload|status}"
   exit 1
  ;;
esac

exit 0
